version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - run: echo "Build done"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Deploying to Production..."

workflows:
  approval_pipeline:
    jobs:
      - build
      - hold_for_approval:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold_for_approval
