version: 2.1

jobs:
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - run: node --version
      - run: npm test

workflows:
  matrix_pipeline:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ["14.21", "16.20", "18.17"]
