version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17   # Official CircleCI Node.js image
    steps:
      - checkout                 # Pull the code from GitHub
      - run: npm install         # Install dependencies
      - run: npm test            # Run tests

workflows:
  simple_pipeline:
    jobs:
      - build-and-test
